dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
      - "@aave=aave/protocol-v2@1.0.1"
networks:
  default: mainnet-fork
  kovan:
    weth_token: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
    lending_pool_addresses_provider: "0x88757f2f99175387ab4c6a4b3067c77a695b0349"
    dai_price_feed: "0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541"
    dai_token: "0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa"
  mainnet-fork:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    lending_pool_addresses_provider: "0xb53c1a33016b2dc2ff3653530bff1848a515c8c5"
    dai_price_feed: "0x773616E4d11A78F511299002da57A0a94577F1f4"
    dai_token: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
  mainnet:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
